project:
  type: website
  resources:
    - 'analysis/*.csv'
    - 'analysis/validation_report.txt'

website:
  title: sgb-data-validator
  favicon: _extensions/Stadt-Geschichte-Basel/sgb-theme/favicon.png
  open-graph: true
  twitter-card: true
  site-url: https://dokumentation.stadtgeschichtebasel.ch/sgb-data-validator/
  repo-url: https://github.com/Stadt-Geschichte-Basel/sgb-data-validator/
  issue-url: https://github.com/Stadt-Geschichte-Basel/sgb-data-validator/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: _extensions/Stadt-Geschichte-Basel/sgb-theme/assets/img/logo.svg
    logo-alt: 'Stadt.Geschichte.Basel Logo'
    title: sgb-data-validator
    tools:
      - icon: github
        url: https://github.com/Stadt-Geschichte-Basel/sgb-data-validator/
    left:
      - text: Readme
        href: index.qmd
      - text: Validation Reports
        href: validation-reports.qmd

  sidebar:
    contents:
      - section: sgb-data-validator
        href: index.qmd
        contents:
          - text: Validation Reports
            href: validation-reports.qmd
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format: sgb-theme-html

freeze: auto

editor: visual
